# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=mipsel -mcpu=r5900 -iterations=1 < %s | FileCheck %s
  .text
  .globl	r5900_basic
  .p2align	3
  .type	r5900_basic,@function
  .ent r5900_basic
r5900_basic:
  .set	noat
  # Integer ALU (1 cycle)
  add	$2, $3, $4
  sub	$5, $6, $7
  and	$8, $9, $10
  or	$11, $12, $13

  # Load/Store (1 cycle)
  lw	$14, 0($sp)
  sw	$15, 4($sp)

  # Multiply (4 cycles)
  mult	$2, $3
  mflo	$4

  # Divide (37 cycles)
  div	$zero, $5, $6
  mflo	$7

  # FPU Add (4 cycles)
  add.s	$f0, $f1, $f2

  # FPU Mul (4 cycles)
  mul.s	$f3, $f4, $f5

  # FPU Div (8 cycles)
  div.s	$f6, $f7, $f8

  # FPU Sqrt (8 cycles)
  sqrt.s	$f9, $f10

  .end	r5900_basic

# CHECK:      Iterations:        1
# CHECK-NEXT: Instructions:      14
# CHECK-NEXT: Total Cycles:      65
# CHECK-NEXT: Total uOps:        14

# CHECK:      Dispatch Width:    2
# CHECK-NEXT: uOps Per Cycle:    0.22
# CHECK-NEXT: IPC:               0.22
# CHECK-NEXT: Block RThroughput: 41.0

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      1     1.00                  U     add	$2, $3, $4
# CHECK-NEXT:  1      1     1.00                  U     sub	$5, $6, $7
# CHECK-NEXT:  1      1     1.00                        and	$8, $9, $10
# CHECK-NEXT:  1      1     1.00                        or	$11, $12, $13
# CHECK-NEXT:  1      1     1.00    *                   lw	$14, 0($sp)
# CHECK-NEXT:  1      1     1.00           *            sw	$15, 4($sp)
# CHECK-NEXT:  1      4     4.00                        mult	$2, $3
# CHECK-NEXT:  1      1     1.00                        mflo	$4
# CHECK-NEXT:  1      37    37.00                 U     div	$zero, $5, $6
# CHECK-NEXT:  1      1     1.00                        mflo	$7
# CHECK-NEXT:  1      4     1.00                        add.s	$f0, $f1, $f2
# CHECK-NEXT:  1      4     1.00                        mul.s	$f3, $f4, $f5
# CHECK-NEXT:  1      8     8.00                        div.s	$f6, $f7, $f8
# CHECK-NEXT:  1      8     8.00                        sqrt.s	$f9, $f10

# CHECK:      Resources:
# CHECK-NEXT: [0]   - R5900Branch
# CHECK-NEXT: [1]   - R5900COP0
# CHECK-NEXT: [2]   - R5900FPU
# CHECK-NEXT: [3]   - R5900FPUDivSqrt
# CHECK-NEXT: [4.0] - R5900IntPipe
# CHECK-NEXT: [4.1] - R5900IntPipe
# CHECK-NEXT: [5]   - R5900IssueALU
# CHECK-NEXT: [6]   - R5900IssueBranch
# CHECK-NEXT: [7]   - R5900IssueCOP0
# CHECK-NEXT: [8]   - R5900IssueFPU
# CHECK-NEXT: [9]   - R5900IssueLDST
# CHECK-NEXT: [10]  - R5900LDST
# CHECK-NEXT: [11]  - R5900MDU
